#! /bin/bash

STAR_FILE=$HOME/.star

if [ $# -ne 1 ]; then
   echo "must provide only a single argument, the star name" >&2
   exit 1
fi

star_name=$1
star_dir=$(grep -m 1 -i "^${star_name}\t" $STAR_FILE | awk -F$'\t' '{print $2}')
if [ -z "$star_dir" ]; then
   echo "no dir found for ${star_name}"
   return 1
fi
echo "$star_dir"

