#! /bin/bash

STAR_FILE=$HOME/.star

if [ $# -ne 1 ] && [ $# -ne 0 ]; then
   echo "usage: starls [optional case sensitive starname regex]" >&2
   exit 1
fi

if [ $# -eq 0 ]; then
    star_pattern=".*"
else
    star_pattern="$1"
fi

# matching only against the star names (not the paths)
# NOTE: it would be great if we could add "BEGIN{IGNORECASE=1}" to the start
# of the program, but this is not supported on OS X' ancient version of awk.
awk -F $'\t' \
  "{ if (\$1 ~ /${star_pattern}/) print }" \
  "$STAR_FILE"

